#!/bin/ksh


function convertReturnValue
{
   typeset rtnVal=$1
   if [[ -z $AMS_RESULTS_DIR ]]
   then
       typeset AMS_RESULTS_DIR="../psf"
   fi
   typeset logFileName="${AMS_RESULTS_DIR}/logFile"
   if [[ "$1" = 1 && -s "$logFileName" ]]
   then
       rtnVal=$2
   fi
   # Supply the value back to the caller.
   return $rtnVal
}

# Set location variables

if [[ -z $AMS_CIC_HIER ]]; then
   export    AMS_CIC_HIER=/share/instsww/cadence/IC.06.17.823
fi

if [[ -z $AMS_IUS_HIER ]]; then
   export    AMS_IUS_HIER=/share/instsww/cadence/INCISIVE.15.20.076
fi

if [[ -z $IC_INVOKE_DIR ]]; then
   export    IC_INVOKE_DIR=/home/cc/ee140/fa19/class/ee140-abc/Documents/ee240-project
fi

export TESTBENCH_TOPCELL="zz_EE140_Fa19_digital"
irun -f irunArgs 


convertReturnValue $? 0

