0 0 dataAuditErrors
2149 0 NWELL_should_be_contacted
2150 0 minority_NWELL_connectors
2151 0 NWELL_soft_connect
2156 0 PTUB_should_be_contacted
2157 0 minority_PTUB_connectors
2158 0 PTUB_soft_connect
2163 0 NDF_should_be_contacted
2164 0 minority_NDF_connectors
2165 0 NDF_soft_connect
2170 0 NBASE_should_be_contacted
2171 0 minority_NBASE_connectors
2172 0 NBASE_soft_connect
2177 0 PDF_should_be_contacted
2178 0 minority_PDF_connectors
2179 0 PDF_soft_connect
2184 0 NDFMV_should_be_contacted
2185 0 minority_NDFMV_connectors
2186 0 NDFMV_soft_connect
2191 0 PDFMV_should_be_contacted
2192 0 minority_PDFMV_connectors
2193 0 PDFMV_soft_connect
2198 0 DFN_should_be_contacted
2199 0 minority_DFN_connectors
2200 0 DFN_soft_connect
2205 0 DFP_should_be_contacted
2206 0 minority_DFP_connectors
2207 0 DFP_soft_connect
2212 0 tiedtub_nbuf_StampErrorFloat
2213 0 tiedtub_nbuf_StampErrorConnect
2214 0 tiedtub_nbuf_StampErrorMult
2219 0 pdfntrm_StampErrorFloat
2220 0 pdfntrm_StampErrorConnect
2221 0 pdfntrm_StampErrorMult
2236 0 handle_wafer_must_have_same_net
2243 0 handle_wafer_contact_is_necessary
2246 0 PWELL4_should_be_contacted
2247 0 minority_PWELL4_connectors
2248 0 PWELL4_soft_connect
2294 0 dfwdnh_an_StampErrorConnect
2295 0 Anode_must_be_have_same_net
2359 0 HWNTUBs_of_Handle_wafer_diodes_must_have_same_net
7298 0 malformed device nem
7299 0 malformed device ndm
7300 0 malformed device pem
7301 0 malformed device pem_5
7302 0 malformed device nnm
7303 0 malformed device pemti
7304 0 malformed device nmva
7305 0 malformed device pmva
7306 0 malformed device phsj1_7
7307 0 malformed device phsj1_10
7308 0 malformed device phsj1_16c
7309 0 malformed device nhvta
7310 0 malformed device nhvtb
7311 0 malformed device nhvu
7312 0 malformed device ndhvt
7313 0 malformed device ndhvta
7314 0 malformed device phvta
7315 0 malformed device phvtb
7316 0 malformed device phvu
7317 0 malformed device nhsj1_7
7318 0 malformed device nhsj1_10
7319 0 malformed device nhsj1_16c
7320 0 malformed device nisj1_16
7321 0 malformed device pmvb
7322 0 malformed device pmvc
7323 0 malformed device pmvd
7324 0 malformed device pmve
7325 0 malformed device pmvf
7326 0 malformed device nhvra
7327 0 malformed device nhvrb
7328 0 malformed device nhvrc
7329 0 malformed device nhvrd
7330 0 malformed device nhvre
7331 0 malformed device nhvrf
7332 0 malformed device ndhvrd
7333 0 malformed device ndhvrf
7334 0 malformed device phvra
7335 0 malformed device phvrb
7336 0 malformed device phvrc
7337 0 malformed device phvrd
7338 0 malformed device phvre
7339 0 malformed device phvrf
7340 0 malformed device ne
7341 0 malformed device nel
7342 0 malformed device pe
7343 0 malformed device pel
7344 0 malformed device pe_5
7345 0 malformed device pel_5
7346 0 malformed device nn
7347 0 malformed device peti
7348 0 malformed device mosvc
7349 0 malformed device mosvci
7350 0 malformed device mosvcm
7351 0 malformed device mosvcim
7352 0 malformed device d_csf2p
7353 0 malformed device d_csf3p
7354 0 malformed device d_csf3
7355 0 malformed device d_csf3a
7356 0 malformed device d_cif3
7357 0 malformed device d_csft4
7358 0 malformed device d_csft4a
7359 0 malformed device d_capsw3
7360 0 malformed device cmm23f
7361 0 malformed device cmm
7362 0 malformed device cmmh23f
7363 0 malformed device cmmh
7364 0 malformed device cdmm
7365 0 malformed device cdmmh
7366 0 malformed device rnw
7367 0 malformed device rnw_scr
7368 0 malformed device rnwm
7369 0 malformed device rnwm_scr
7370 0 malformed device rxw2ti
7371 0 malformed device rnp1h_1
7372 0 malformed device rnp1h_3_pw
7373 0 malformed device rnp1h_3_nw
7374 0 malformed device rpp1k1_1
7375 0 malformed device rpp1k1_3_pw
7376 0 malformed device rpp1k1_3_nw
7377 0 malformed device rpp1k1a_1
7378 0 malformed device rpp1k1a_3_pw
7379 0 malformed device rpp1k1a_3_nw
7380 0 malformed device rnp1_1
7381 0 malformed device rnp1_3_pw
7382 0 malformed device rnp1_3_nw
7383 0 malformed device rpp1_1
7384 0 malformed device rpp1_3_pw
7385 0 malformed device rpp1_3_nw
7386 0 malformed device rpp1s_1
7387 0 malformed device rpp1s_3_pw
7388 0 malformed device rpp1s_3_nw
7389 0 malformed device rdn
7390 0 malformed device rdn_g
7391 0 malformed device rdp
7392 0 malformed device rdp_g
7393 0 malformed device rdnm
7394 0 malformed device rdnm_g
7395 0 malformed device rdnm_pw4
7396 0 malformed device rdnm_dpc
7397 0 malformed device rdpm
7398 0 malformed device rdpm_g
7399 0 malformed device met1res
7400 0 malformed device met2res
7401 0 malformed device met3res
7402 0 malformed device mtpres
8558 0 unstable device for mt_vm25_Device_209
8559 0 unpreserved device mt_vm25_Device_209
8560 0 unstable device for mt_vm60_Device_208
8561 0 unpreserved device mt_vm60_Device_208
8562 0 unstable device for mt_vm100_Device_207
8563 0 unpreserved device mt_vm100_Device_207
8564 0 unstable device for mt_vm200_Device_206
8565 0 unpreserved device mt_vm200_Device_206
8566 0 unstable device for mt_v25_Device_205
8567 0 unpreserved device mt_v25_Device_205
8568 0 unstable device for mt_v60_Device_204
8569 0 unpreserved device mt_v60_Device_204
8570 0 unstable device for mt_v100_Device_203
8571 0 unpreserved device mt_v100_Device_203
8572 0 unstable device for mt_v200_Device_202
8573 0 unpreserved device mt_v200_Device_202
8574 0 unstable device for m3_vm25_Device_201
8575 0 unpreserved device m3_vm25_Device_201
8576 0 unstable device for m3_vm60_Device_200
8577 0 unpreserved device m3_vm60_Device_200
8578 0 unstable device for m3_vm100_Device_199
8579 0 unpreserved device m3_vm100_Device_199
8580 0 unstable device for m3_vm200_Device_198
8581 0 unpreserved device m3_vm200_Device_198
8582 0 unstable device for m3_v25_Device_197
8583 0 unpreserved device m3_v25_Device_197
8584 0 unstable device for m3_v60_Device_196
8585 0 unpreserved device m3_v60_Device_196
8586 0 unstable device for m3_v100_Device_195
8587 0 unpreserved device m3_v100_Device_195
8588 0 unstable device for m3_v200_Device_194
8589 0 unpreserved device m3_v200_Device_194
8590 0 unstable device for m2_vm25_Device_193
8591 0 unpreserved device m2_vm25_Device_193
8592 0 unstable device for m2_vm60_Device_192
8593 0 unpreserved device m2_vm60_Device_192
8594 0 unstable device for m2_vm100_Device_191
8595 0 unpreserved device m2_vm100_Device_191
8596 0 unstable device for m2_vm200_Device_190
8597 0 unpreserved device m2_vm200_Device_190
8598 0 unstable device for m2_v25_Device_189
8599 0 unpreserved device m2_v25_Device_189
8600 0 unstable device for m2_v60_Device_188
8601 0 unpreserved device m2_v60_Device_188
8602 0 unstable device for m2_v100_Device_187
8603 0 unpreserved device m2_v100_Device_187
8604 0 unstable device for m2_v200_Device_186
8605 0 unpreserved device m2_v200_Device_186
8606 0 unstable device for m1_vm25_Device_185
8607 0 unpreserved device m1_vm25_Device_185
8608 0 unstable device for m1_vm60_Device_184
8609 0 unpreserved device m1_vm60_Device_184
8610 0 unstable device for m1_vm100_Device_183
8611 0 unpreserved device m1_vm100_Device_183
8612 0 unstable device for m1_vm200_Device_182
8613 0 unpreserved device m1_vm200_Device_182
8614 0 unstable device for m1_v25_Device_181
8615 0 unpreserved device m1_v25_Device_181
8616 0 unstable device for m1_v60_Device_180
8617 0 unpreserved device m1_v60_Device_180
8618 0 unstable device for m1_v100_Device_179
8619 0 unpreserved device m1_v100_Device_179
8620 0 unstable device for m1_v200_Device_178
8621 0 unpreserved device m1_v200_Device_178
8622 0 unstable device for p1_vm25_Device_177
8623 0 unpreserved device p1_vm25_Device_177
8624 0 unstable device for p1_vm60_Device_176
8625 0 unpreserved device p1_vm60_Device_176
8626 0 unstable device for p1_vm100_Device_175
8627 0 unpreserved device p1_vm100_Device_175
8628 0 unstable device for p1_vm200_Device_174
8629 0 unpreserved device p1_vm200_Device_174
8630 0 unstable device for p1_v25_Device_173
8631 0 unpreserved device p1_v25_Device_173
8632 0 unstable device for p1_v60_Device_172
8633 0 unpreserved device p1_v60_Device_172
8634 0 unstable device for p1_v100_Device_171
8635 0 unpreserved device p1_v100_Device_171
8636 0 unstable device for p1_v200_Device_170
8637 0 unpreserved device p1_v200_Device_170
8638 0 unstable device for p_dnwmmva_DIODE_169
8639 0 unpreserved device p_dnwmmva_DIODE_169
8640 0 unstable device for p_dnnm_DIODE_166
8641 0 unpreserved device p_dnnm_DIODE_166
8642 0 unstable device for p_dnm_DIODE_165
8643 0 unpreserved device p_dnm_DIODE_165
8644 0 unstable device for p_dpm_DIODE_164
8645 0 unpreserved device p_dpm_DIODE_164
8646 0 unstable device for p_dpm_DIODE_168
8647 0 unpreserved device p_dpm_DIODE_168
8648 0 unstable device for p_dnwm_DIODE_163
8649 0 unpreserved device p_dnwm_DIODE_163
8650 0 unstable device for p_dnwm_DIODE_167
8651 0 unpreserved device p_dnwm_DIODE_167
8652 0 unstable device for p_dnn_DIODE_160
8653 0 unpreserved device p_dnn_DIODE_160
8654 0 unstable device for p_dn_DIODE_159
8655 0 unpreserved device p_dn_DIODE_159
8656 0 unstable device for p_dp_DIODE_158
8657 0 unpreserved device p_dp_DIODE_158
8658 0 unstable device for p_dp_DIODE_162
8659 0 unpreserved device p_dp_DIODE_162
8660 0 unstable device for p_dnw_DIODE_157
8661 0 unpreserved device p_dnw_DIODE_157
8662 0 unstable device for p_dnw_DIODE_161
8663 0 unpreserved device p_dnw_DIODE_161
8664 0 unstable device for dfwdnhf_DIODE_156
8665 0 unpreserved device dfwdnhf_DIODE_156
8666 0 unstable device for dfwdnhe_DIODE_155
8667 0 unpreserved device dfwdnhe_DIODE_155
8668 0 unstable device for dfwdnhd_DIODE_154
8669 0 unpreserved device dfwdnhd_DIODE_154
8670 0 unstable device for dfwdnhc_DIODE_153
8671 0 unpreserved device dfwdnhc_DIODE_153
8672 0 unstable device for dfwdnu_DIODE_152
8673 0 unpreserved device dfwdnu_DIODE_152
8674 0 unstable device for dfwdnt_DIODE_151
8675 0 unpreserved device dfwdnt_DIODE_151
8676 0 unstable device for dzb_DIODE_150
8677 0 unpreserved device dzb_DIODE_150
8678 0 unstable device for dfwdn5_DIODE_149
8679 0 unpreserved device dfwdn5_DIODE_149
8680 0 unstable device for dzati_DIODE_148
8681 0 unpreserved device dzati_DIODE_148
8682 0 unstable device for dza_DIODE_147
8683 0 unpreserved device dza_DIODE_147
8684 0 unstable device for dnpati_DIODE_146
8685 0 unpreserved device dnpati_DIODE_146
8686 0 unstable device for dnpa_DIODE_145
8687 0 unpreserved device dnpa_DIODE_145
8688 0 unstable device for ds5a_DIODE_144
8689 0 unpreserved device ds5a_DIODE_144
8690 0 unstable device for dnp7_DIODE_143
8691 0 unpreserved device dnp7_DIODE_143
8692 0 unstable device for dpp7_DIODE_142
8693 0 unpreserved device dpp7_DIODE_142
8694 0 unstable device for dpp6_DIODE_141
8695 0 unpreserved device dpp6_DIODE_141
8696 0 unstable device for dhw3_dev_DIODE_140
8697 0 unpreserved device dhw3_dev_DIODE_140
8698 0 unstable device for dhw2_dev_DIODE_139
8699 0 unpreserved device dhw2_dev_DIODE_139
8700 0 unstable device for dhw2a_dev_DIODE_138
8701 0 unpreserved device dhw2a_dev_DIODE_138
8702 0 unstable device for dfwnsj1_16c_DIODE_137
8703 0 unpreserved device dfwnsj1_16c_DIODE_137
8704 0 unstable device for dfwnsj1_10_DIODE_136
8705 0 unpreserved device dfwnsj1_10_DIODE_136
8706 0 unstable device for dfwnsj1_7_DIODE_135
8707 0 unpreserved device dfwnsj1_7_DIODE_135
8708 0 unstable device for dfwdp2f_DIODE_134
8709 0 unpreserved device dfwdp2f_DIODE_134
8710 0 unstable device for dfwdp1f_DIODE_133
8711 0 unpreserved device dfwdp1f_DIODE_133
8712 0 unstable device for d_dnwm_DIODE_130
8713 0 unpreserved device d_dnwm_DIODE_130
8714 0 unstable device for d_dnwm_DIODE_132
8715 0 unpreserved device d_dnwm_DIODE_132
8716 0 unstable device for d_dnnm_DIODE_129
8717 0 unpreserved device d_dnnm_DIODE_129
8718 0 unstable device for d_dnm_DIODE_128
8719 0 unpreserved device d_dnm_DIODE_128
8720 0 unstable device for d_dpm_DIODE_127
8721 0 unpreserved device d_dpm_DIODE_127
8722 0 unstable device for d_dpm_DIODE_131
8723 0 unpreserved device d_dpm_DIODE_131
8724 0 unstable device for d_dnw_DIODE_124
8725 0 unpreserved device d_dnw_DIODE_124
8726 0 unstable device for d_dnw_DIODE_126
8727 0 unpreserved device d_dnw_DIODE_126
8728 0 unstable device for d_dnn_DIODE_123
8729 0 unpreserved device d_dnn_DIODE_123
8730 0 unstable device for d_dn_DIODE_122
8731 0 unpreserved device d_dn_DIODE_122
8732 0 unstable device for d_dp_DIODE_121
8733 0 unpreserved device d_dp_DIODE_121
8734 0 unstable device for d_dp_DIODE_125
8735 0 unpreserved device d_dp_DIODE_125
8736 0 unstable device for qpv5_BJT_120
8737 0 unpreserved device qpv5_BJT_120
8738 0 unstable device for qnv5_BJT_119
8739 0 unpreserved device qnv5_BJT_119
8740 0 unstable device for qpvme_BJT_118
8741 0 unpreserved device qpvme_BJT_118
8742 0 unstable device for qpvmf_BJT_117
8743 0 unpreserved device qpvmf_BJT_117
8744 0 unstable device for qpvmg_BJT_116
8745 0 unpreserved device qpvmg_BJT_116
8746 0 unstable device for qpvma_BJT_115
8747 0 unpreserved device qpvma_BJT_115
8748 0 unstable device for qpvmb_BJT_114
8749 0 unpreserved device qpvmb_BJT_114
8750 0 unstable device for qpvmc_BJT_113
8751 0 unpreserved device qpvmc_BJT_113
8752 0 unstable device for qpve_BJT_112
8753 0 unpreserved device qpve_BJT_112
8754 0 unstable device for qpvf_BJT_111
8755 0 unpreserved device qpvf_BJT_111
8756 0 unstable device for qpvg_BJT_110
8757 0 unpreserved device qpvg_BJT_110
8758 0 unstable device for qpva_BJT_109
8759 0 unpreserved device qpva_BJT_109
8760 0 unstable device for qpvb_BJT_108
8761 0 unpreserved device qpvb_BJT_108
8762 0 unstable device for qpvc_BJT_107
8763 0 unpreserved device qpvc_BJT_107
8764 0 unstable device for pfuse_RES_106
8765 0 unpreserved device pfuse_RES_106
8766 0 unstable device for mtpres_RES_105
8767 0 unpreserved device mtpres_RES_105
8768 0 unstable device for met3res_RES_104
8769 0 unpreserved device met3res_RES_104
8770 0 unstable device for met2res_RES_103
8771 0 unpreserved device met2res_RES_103
8772 0 unstable device for met1res_RES_102
8773 0 unpreserved device met1res_RES_102
8774 0 unstable device for rdpm_g_RES_101
8775 0 unpreserved device rdpm_g_RES_101
8776 0 unstable device for rdpm_RES_100
8777 0 unpreserved device rdpm_RES_100
8778 0 unstable device for rdnm_dpc_RES_99
8779 0 unpreserved device rdnm_dpc_RES_99
8780 0 unstable device for rdnm_pw4_RES_98
8781 0 unpreserved device rdnm_pw4_RES_98
8782 0 unstable device for rdnm_g_RES_97
8783 0 unpreserved device rdnm_g_RES_97
8784 0 unstable device for rdnm_RES_96
8785 0 unpreserved device rdnm_RES_96
8786 0 unstable device for rdp_g_RES_95
8787 0 unpreserved device rdp_g_RES_95
8788 0 unstable device for rdp_RES_94
8789 0 unpreserved device rdp_RES_94
8790 0 unstable device for rdn_g_RES_93
8791 0 unpreserved device rdn_g_RES_93
8792 0 unstable device for rdn_RES_92
8793 0 unpreserved device rdn_RES_92
8794 0 unstable device for rpp1s_3_nw_RES_91
8795 0 unpreserved device rpp1s_3_nw_RES_91
8796 0 unstable device for rpp1s_3_pw_RES_90
8797 0 unpreserved device rpp1s_3_pw_RES_90
8798 0 unstable device for rpp1s_1_RES_89
8799 0 unpreserved device rpp1s_1_RES_89
8800 0 unstable device for rpp1_3_nw_RES_88
8801 0 unpreserved device rpp1_3_nw_RES_88
8802 0 unstable device for rpp1_3_pw_RES_87
8803 0 unpreserved device rpp1_3_pw_RES_87
8804 0 unstable device for rpp1_1_RES_86
8805 0 unpreserved device rpp1_1_RES_86
8806 0 unstable device for rnp1_3_nw_RES_85
8807 0 unpreserved device rnp1_3_nw_RES_85
8808 0 unstable device for rnp1_3_pw_RES_84
8809 0 unpreserved device rnp1_3_pw_RES_84
8810 0 unstable device for rnp1_1_RES_83
8811 0 unpreserved device rnp1_1_RES_83
8812 0 unstable device for rpp1k1a_3_nw_RES_82
8813 0 unpreserved device rpp1k1a_3_nw_RES_82
8814 0 unstable device for rpp1k1a_3_pw_RES_81
8815 0 unpreserved device rpp1k1a_3_pw_RES_81
8816 0 unstable device for rpp1k1a_1_RES_80
8817 0 unpreserved device rpp1k1a_1_RES_80
8818 0 unstable device for rpp1k1_3_nw_RES_79
8819 0 unpreserved device rpp1k1_3_nw_RES_79
8820 0 unstable device for rpp1k1_3_pw_RES_78
8821 0 unpreserved device rpp1k1_3_pw_RES_78
8822 0 unstable device for rpp1k1_1_RES_77
8823 0 unpreserved device rpp1k1_1_RES_77
8824 0 unstable device for rnp1h_3_nw_RES_76
8825 0 unpreserved device rnp1h_3_nw_RES_76
8826 0 unstable device for rnp1h_3_pw_RES_75
8827 0 unpreserved device rnp1h_3_pw_RES_75
8828 0 unstable device for rnp1h_1_RES_74
8829 0 unpreserved device rnp1h_1_RES_74
8830 0 unstable device for rxw2ti_RES_73
8831 0 unpreserved device rxw2ti_RES_73
8832 0 unstable device for rnwm_scr_RES_72
8833 0 unpreserved device rnwm_scr_RES_72
8834 0 unstable device for rnwm_RES_71
8835 0 unpreserved device rnwm_RES_71
8836 0 unstable device for rnw_scr_RES_70
8837 0 unpreserved device rnw_scr_RES_70
8838 0 unstable device for rnw_RES_69
8839 0 unpreserved device rnw_RES_69
8840 0 unstable device for cdmmh_CAP_68
8841 0 unpreserved device cdmmh_CAP_68
8842 0 unstable device for cdmm_CAP_67
8843 0 unpreserved device cdmm_CAP_67
8844 0 unstable device for cmmh_CAP_66
8845 0 unpreserved device cmmh_CAP_66
8846 0 unstable device for cmmh23f_CAP_65
8847 0 unpreserved device cmmh23f_CAP_65
8848 0 unstable device for cmm_CAP_64
8849 0 unpreserved device cmm_CAP_64
8850 0 unstable device for cmm23f_CAP_63
8851 0 unpreserved device cmm23f_CAP_63
8852 0 unstable device for d_capsw3_CAP_62
8853 0 unpreserved device d_capsw3_CAP_62
8854 0 unstable device for d_csft4a_CAP_61
8855 0 unpreserved device d_csft4a_CAP_61
8856 0 unstable device for d_csft4_CAP_60
8857 0 unpreserved device d_csft4_CAP_60
8858 0 unstable device for d_cif3_CAP_59
8859 0 unpreserved device d_cif3_CAP_59
8860 0 unstable device for d_csf3a_CAP_58
8861 0 unpreserved device d_csf3a_CAP_58
8862 0 unstable device for d_csf3_CAP_57
8863 0 unpreserved device d_csf3_CAP_57
8864 0 unstable device for d_csf3p_CAP_56
8865 0 unpreserved device d_csf3p_CAP_56
8866 0 unstable device for d_csf2p_CAP_55
8867 0 unpreserved device d_csf2p_CAP_55
8868 0 unstable device for mosvcim_Device_54
8869 0 unpreserved device mosvcim_Device_54
8870 0 unstable device for mosvcm_Device_53
8871 0 unpreserved device mosvcm_Device_53
8872 0 unstable device for mosvci_Device_52
8873 0 unpreserved device mosvci_Device_52
8874 0 unstable device for mosvc_Device_51
8875 0 unpreserved device mosvc_Device_51
8876 0 unstable device for peti_MOS_50
8877 0 unpreserved device peti_MOS_50
8878 0 unstable device for nn_MOS_49
8879 0 unpreserved device nn_MOS_49
8880 0 unstable device for pel_5_Device_48
8881 0 unpreserved device pel_5_Device_48
8882 0 unstable device for pe_5_Device_47
8883 0 unpreserved device pe_5_Device_47
8884 0 unstable device for pel_MOS_46
8885 0 unpreserved device pel_MOS_46
8886 0 unstable device for pe_MOS_45
8887 0 unpreserved device pe_MOS_45
8888 0 unstable device for nel_MOS_44
8889 0 unpreserved device nel_MOS_44
8890 0 unstable device for ne_MOS_43
8891 0 unpreserved device ne_MOS_43
8892 0 unstable device for phvrf_Device_42
8893 0 unpreserved device phvrf_Device_42
8894 0 unstable device for phvre_Device_41
8895 0 unpreserved device phvre_Device_41
8896 0 unstable device for phvrd_Device_40
8897 0 unpreserved device phvrd_Device_40
8898 0 unstable device for phvrc_Device_39
8899 0 unpreserved device phvrc_Device_39
8900 0 unstable device for phvrb_Device_38
8901 0 unpreserved device phvrb_Device_38
8902 0 unstable device for phvra_Device_37
8903 0 unpreserved device phvra_Device_37
8904 0 unstable device for ndhvrf_Device_36
8905 0 unpreserved device ndhvrf_Device_36
8906 0 unstable device for ndhvrd_Device_35
8907 0 unpreserved device ndhvrd_Device_35
8908 0 unstable device for nhvrf_Device_34
8909 0 unpreserved device nhvrf_Device_34
8910 0 unstable device for nhvre_Device_33
8911 0 unpreserved device nhvre_Device_33
8912 0 unstable device for nhvrd_Device_32
8913 0 unpreserved device nhvrd_Device_32
8914 0 unstable device for nhvrc_Device_31
8915 0 unpreserved device nhvrc_Device_31
8916 0 unstable device for nhvrb_Device_30
8917 0 unpreserved device nhvrb_Device_30
8918 0 unstable device for nhvra_Device_29
8919 0 unpreserved device nhvra_Device_29
8920 0 unstable device for pmvf_Device_28
8921 0 unpreserved device pmvf_Device_28
8922 0 unstable device for pmve_Device_27
8923 0 unpreserved device pmve_Device_27
8924 0 unstable device for pmvd_Device_26
8925 0 unpreserved device pmvd_Device_26
8926 0 unstable device for pmvc_Device_25
8927 0 unpreserved device pmvc_Device_25
8928 0 unstable device for pmvb_Device_24
8929 0 unpreserved device pmvb_Device_24
8930 0 unstable device for nisj1_16_Device_23
8931 0 unpreserved device nisj1_16_Device_23
8932 0 unstable device for nhsj1_16c_Device_22
8933 0 unpreserved device nhsj1_16c_Device_22
8934 0 unstable device for nhsj1_10_Device_21
8935 0 unpreserved device nhsj1_10_Device_21
8936 0 unstable device for nhsj1_7_Device_20
8937 0 unpreserved device nhsj1_7_Device_20
8938 0 unstable device for phvu_Device_19
8939 0 unpreserved device phvu_Device_19
8940 0 unstable device for phvtb_Device_18
8941 0 unpreserved device phvtb_Device_18
8942 0 unstable device for phvta_Device_17
8943 0 unpreserved device phvta_Device_17
8944 0 unstable device for ndhvta_Device_16
8945 0 unpreserved device ndhvta_Device_16
8946 0 unstable device for ndhvt_Device_15
8947 0 unpreserved device ndhvt_Device_15
8948 0 unstable device for nhvu_Device_14
8949 0 unpreserved device nhvu_Device_14
8950 0 unstable device for nhvtb_Device_13
8951 0 unpreserved device nhvtb_Device_13
8952 0 unstable device for nhvta_Device_12
8953 0 unpreserved device nhvta_Device_12
8954 0 unstable device for phsj1_16c_Device_11
8955 0 unpreserved device phsj1_16c_Device_11
8956 0 unstable device for phsj1_10_Device_10
8957 0 unpreserved device phsj1_10_Device_10
8958 0 unstable device for phsj1_7_Device_9
8959 0 unpreserved device phsj1_7_Device_9
8960 0 unstable device for pmva_Device_8
8961 0 unpreserved device pmva_Device_8
8962 0 unstable device for nmva_Device_7
8963 0 unpreserved device nmva_Device_7
8964 0 unstable device for pemti_MOS_6
8965 0 unpreserved device pemti_MOS_6
8966 0 unstable device for nnm_MOS_5
8967 0 unpreserved device nnm_MOS_5
8968 0 unstable device for pem_5_Device_4
8969 0 unpreserved device pem_5_Device_4
8970 0 unstable device for pem_MOS_3
8971 0 unpreserved device pem_MOS_3
8972 0 unstable device for ndm_MOS_2
8973 0 unpreserved device ndm_MOS_2
8974 0 unstable device for nem_MOS_1
8975 0 unpreserved device nem_MOS_1
